### ISSUE TITLE
Infinite Recursion with custom query class during instantiation of QuerySelectMultipleField

### ISSUE THREAD

**Issue by cacampbell** [pallets-eco/flask-admin#1469]
Hi, 

The actual problem with the situation described in [Issue 1468](https://github.com/flask-admin/flask-admin/issues/1468) is that when I use a query select function that "should" work, it triggers infinite recursion. 

So, if I use this query factory:

```
lambda: [model].query.options(FromCache(cache=cache)).all()
# 'query' is CachingQuery from Flask-SQLAlchemy-Cache
```
with CachingQuery from Flask-SQLAlchemy-Cache, max iterations of recursion are reached while instantiating the queryselectmultiplefield

```
127.0.0.1 - - [12/Apr/2017 16:21:11] "GET /paper/new/?url=%2Fpaper%2F HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/usr/lib/python3.5/cProfile.py", line 109, in runcall
    return func(*args, **kw)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/cacampbell/PycharmProjects/coniferbook/app/auth/model_views.py", line 927, in create_view
    return_url=return_url)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 3, in top-level template code
    {% from 'admin/lib.html' import extra with context %} {# backward compatible #}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/home/cacampbell/PycharmProjects/coniferbook/app/templates/auth/base.html", line 148, in top-level template code
    <img src="{{ url_for('static', filename='images/loading.gif') }}" />
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 37, in top-level template code
    {% block page_body %}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/base.html", line 77, in block "page_body"
    {% block body %}{% endblock %}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 22, in block "body"
    {% block create_form %}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/model/create.html", line 23, in block "create_form"
    {{ lib.render_form(form, return_url, extra(), form_opts) }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 202, in template
    {% call form_tag(action=action) %}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 182, in template
    {{ caller() }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 203, in template
    {{ render_form_fields(form, form_opts=form_opts) }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 175, in template
    {{ render_field(form, f, kwargs) }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/jinja2/runtime.py", line 551, in _invoke
    rv = self._func(*arguments)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/templates/bootstrap3/admin/lib.html", line 130, in template
    {{ field(**kwargs)|safe }}
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/wtforms/fields/core.py", line 153, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/form/widgets.py", line 28, in __call__
    return super(Select2Widget, self).__call__(field, **kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/wtforms/widgets/core.py", line 287, in __call__
    for val, label, selected in field.iter_choices():
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/contrib/sqla/fields.py", line 168, in iter_choices
    for pk, obj in self._get_object_list():
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_admin/contrib/sqla/fields.py", line 100, in _get_object_list
    query = self.query or self.query_factory()
  File "/home/cacampbell/PycharmProjects/coniferbook/app/auth/forms.py", line 23, in <lambda>
    return lambda: model.query.options(FromCache(cache=cache)).all()
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2703, in all
    return list(self)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_sqlalchemy_cache/core.py", line 48, in __iter__
    return iter(self.get_value(createfunc=func))
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_sqlalchemy_cache/core.py", line 84, in get_value
    cache.set(cache_key, cached_value, timeout=expiration_time)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/flask_cache/__init__.py", line 200, in set
    self.cache.set(*args, **kwargs)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/werkzeug/contrib/cache.py", line 317, in set
    pickle.HIGHEST_PROTOCOL))
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 439, in __getstate__
    state_dict['manager'] = self.manager._serialize(self, state_dict)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/sqlalchemy/orm/instrumentation.py", line 327, in _serialize
    return _SerializeManager(state, state_dict)
  File "/home/cacampbell/.virtualenvs/coniferbook/lib/python3.5/site-packages/sqlalchemy/orm/instrumentation.py", line 380, in __init__
    manager.dispatch.pickle(state, d)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ljluestc** [comment]
```

from flask_sqlalchemy_cache import CachingQuery, FromCache
from flask_admin.contrib.sqla.fields import QuerySelectMultipleField

# Your model query
def query_factory():
    return model.query.options(FromCache(cache=cache)).all()

# Ensure the cache is only applied when needed and not during the form instantiation
class CustomQuerySelectMultipleField(QuerySelectMultipleField):
    def __init__(self, label=None, validators=None, query_factory=None, **kwargs):
        super().__init__(label, validators, query_factory=query_factory, **kwargs)

    def iter_choices(self):
        # Directly use the query result without triggering recursion
        for obj in self.query_factory():
            yield (obj.id, obj.name, False)  # Assuming your model has 'id' and 'name' fields

# Applying the custom field
class YourForm(FlaskForm):
    your_field = CustomQuerySelectMultipleField(
        label='Your Label',
        query_factory=query_factory
    )
```
