### ISSUE TITLE
example sqla from readme.md is broken

### ISSUE THREAD

**Issue by jugmac00** [pallets-eco/flask-admin#1766]
I followed the steps from the example section from the readme.md.

And at step 4 I get
`(venv) jugmac00@DESKTOP-jugmac00:~/Projects/flask-admin$ python examples/sqla/app.py
/home/jugmac00/Projects/flask-admin/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "examples/sqla/app.py", line 266, in <module>
    admin.add_sub_category(name="Links", parent_name="Other")
AttributeError: 'Admin' object has no attribute 'add_sub_category'
(venv) jugmac00@DESKTOP-jugmac00:~/Projects/flask-admin$`

This happens on Ubuntu 18.04 with Python 3.6.7 (both with stock pip and with updated pip version).

Reproduce:
`$ git clone https://github.com/flask-admin/flask-admin.git

$ cd flask-admin/

$ python3 -m venv venv

$ pip install -U pip # optionally

$ pip install -r 'examples/sqla/requirements.txt'

$ python examples/sqla/app.py
`

**Comment by stefkes** [comment]
Exact same problem for me

**Comment by jugmac00** [comment]
I just wanted to check whether this has been fixed and now this fails with another error:

```
flask-admin on  master via 🐍 v3.6.9 (venv) took 6s 
❯ python examples/sqla/run_server.py 
Traceback (most recent call last):
  File "examples/sqla/run_server.py", line 1, in <module>
    from admin import app
  File "/home/jugmac00/Projects/flask-admin/examples/sqla/admin/__init__.py", line 2, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
```

**Comment by ElLorans** [comment]
The original issue looked to be due to a version incompatibility between the installed flask-admin and the example. The last comment was caused by not installing the requirements, in particular, `flask-sqlalchemy.` Installing the requirements of the example (without having flask-babel installed) works for me. I am closing the issue since I cannot reproduce.
