### ISSUE TITLE
BaseModelView.get_list_value missing positional argument 'name'

### ISSUE THREAD

**Issue by cspital** [pallets-eco/flask-admin#1827]
I'm trying to intercept the model en route to the list form so i can eliminate a field's contents.

Flask==1.0.2
Flask-Admin==1.5.3
Flask-PyMongo==2.2.0
WTForms==2.2.1

```
from flask_admin import Admin

from wtforms import form, fields, validators

from flask_admin.contrib.pymongo import ModelView
from modules.app import mongo, app
import uuid
from flask_pymongo import ObjectId

class ClientForm(form.Form):
    name = fields.StringField('Name', [validators.DataRequired()])
    token = fields.StringField(
        'Token', [validators.DataRequired()], default=lambda: str(uuid.uuid4()))

class ClientView(ModelView):
    column_list = ('name', 'token')
    column_sortable_list = ('name',)

    form = ClientForm

    def get_list_value(self, context, model, name):
        return super().get_list_value(context, model, name)

admin = Admin(app, name='User Portal Admin Panel')
admin.add_view(ClientView(mongo.db.clients, 'Clients'))
```

Throws:
```
Traceback (most recent call last):
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/model/base.py", line 2056, in index_view
    return_url=self._get_list_url(view_args),
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/base.py", line 308, in render
    return render_template(template, **kwargs)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/model/list.html", line 6, in top-level template code
    {% import 'admin/model/row_actions.html' as row_actions with context %}
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 35, in top-level template code
    {% block page_body %}
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 64, in block "page_body"
    {% block body %}{% endblock %}
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/model/list.html", line 69, in block "body"
    {% block model_list_table %}
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/model/list.html", line 117, in block "model_list_table"
    {% block list_row scoped %}
  File "/Users/myaccount/.local/share/virtualenvs/admin-user-portal-ZRBNBe-H/lib/python3.6/site-packages/flask_admin/templates/bootstrap2/admin/model/list.html", line 145, in block "list_row"
    {{ get_value(row, c) }}
TypeError: get_list_value() missing 1 required positional argument: 'name'
```

**Comment by milesgranger** [comment]
Issue still present it seems for me as well.
Ref docs: https://flask-admin.readthedocs.io/en/latest/api/mod_contrib_peewee/#flask_admin.contrib.peewee.ModelView.get_list_value

**Comment by milesgranger** [comment]
Removing the `context` from the signature, and passing `None` to parent for context seems to work.
```python
def get_list_value(self, model, name):
        return super().get_list_value(None, model, name)
```
