### ISSUE TITLE
sqla example fails with Invalid field User.phone_number error

### ISSUE THREAD

**Issue by dreed47** [pallets-eco/flask-admin#1896]
Running the sqla example produces the following error.  One issue is that the db does not get created when it doesn't exist.  It looks like a recent restructuring of the code likely caused this issue.

```
Traceback (most recent call last):
File "examples/sqla/run_server.py", line 1, in
from admin import app
File "C:\Users\mhamelin\PycharmProjects\untitled9\flask-admin\examples\sqla\admin_init_.py", line 24, in
import admin.main
File "C:\Users\mhamelin\PycharmProjects\untitled9\flask-admin\examples\sqla\admin\main.py", line 248, in
admin.add_view(UserAdmin(User, db.session))
File "C:\Users\mhamelin\PycharmProjects\untitled9\venv\lib\site-packages\flask_admin\contrib\sqla\view.py", line 329, in
init
menu_icon_value=menu_icon_value)
File "C:\Users\mhamelin\PycharmProjects\untitled9\venv\lib\site-packages\flask_admin\model\base.py", line 818, in _init
_
self._refresh_cache()
File "C:\Users\mhamelin\PycharmProjects\untitled9\venv\lib\site-packages\flask_admin\model\base.py", line 913, in _refres
h_cache
self._search_supported = self.init_search()
File "C:\Users\mhamelin\PycharmProjects\untitled9\venv\lib\site-packages\flask_admin\contrib\sqla\view.py", line 578, in
init_search
for column in tools.get_columns_for_field(attr):
File "C:\Users\mhamelin\PycharmProjects\untitled9\venv\lib\site-packages\flask_admin\contrib\sqla\tools.py", line 123, in
get_columns_for_field
raise Exception('Invalid field %s: does not contains any columns.' % field)
Exception: Invalid field User.phone_number: does not contains any columns.
```

**Comment by etpu** [comment]
Me too
`(venv) C:\project\flask-admin\examples\sqla>flask run
 * Serving Flask app "run_server.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "C:\Users\Art\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Art\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\project\flask-admin\venv\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\project\flask-admin\venv\lib\site-packages\flask\cli.py", line 966, in main
    cli.main(prog_name="python -m flask" if as_module else None)
  File "c:\project\flask-admin\venv\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\project\flask-admin\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\project\flask-admin\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\project\flask-admin\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\project\flask-admin\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\project\flask-admin\venv\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\project\flask-admin\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\project\flask-admin\venv\lib\site-packages\flask\cli.py", line 848, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "c:\project\flask-admin\venv\lib\site-packages\flask\cli.py", line 305, in __init__
    self._load_unlocked()
  File "c:\project\flask-admin\venv\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "c:\project\flask-admin\venv\lib\site-packages\flask\cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "c:\project\flask-admin\venv\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "C:\project\flask-admin\examples\sqla\run_server.py", line 1, in <module>
    from admin import app
  File "C:\project\flask-admin\examples\sqla\admin\__init__.py", line 24, in <module>
    import admin.main
  File "C:\project\flask-admin\examples\sqla\admin\main.py", line 248, in <module>
    admin.add_view(UserAdmin(User, db.session))
  File "c:\project\flask-admin\venv\lib\site-packages\flask_admin\contrib\sqla\view.py", line 329, in __init__
    menu_icon_value=menu_icon_value)
  File "c:\project\flask-admin\venv\lib\site-packages\flask_admin\model\base.py", line 818, in __init__
    self._refresh_cache()
  File "c:\project\flask-admin\venv\lib\site-packages\flask_admin\model\base.py", line 913, in _refresh_cache
    self._search_supported = self.init_search()
  File "c:\project\flask-admin\venv\lib\site-packages\flask_admin\contrib\sqla\view.py", line 578, in init_search
    for column in tools.get_columns_for_field(attr):
  File "c:\project\flask-admin\venv\lib\site-packages\flask_admin\contrib\sqla\tools.py", line 123, in get_columns_for_field
    raise Exception('Invalid field %s: does not contains any columns.' % field)
Exception: Invalid field User.phone_number: does not contains any columns.`

**Comment by hushaoqing** [comment]
try this: https://github.com/flask-admin/flask-admin/issues/1881#issuecomment-508642931

**Comment by ElLorans** [comment]
The issue looks to be solved by now.
