### ISSUE TITLE
flask-admin throwing `'get_flashed_messages' is undefined` on setup

### ISSUE THREAD

**Issue by wjordan213** [pallets-eco/flask-admin#1969]
Having just installed flask-admin into my flask environment running Python 3.8, I see the following error when accessing the "/admin" URL:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_admin/base.py", line 451, in index
    return self.render(self._template)
  File "/usr/local/lib/python3.8/site-packages/flask_admin/base.py", line 307, in render
    return render_template(template, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.8/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/flask_admin/templates/bootstrap2/admin/index.html", line 1, in <module>
    {% extends 'admin/master.html' %}
  File "/usr/local/lib/python3.8/site-packages/flask_admin/templates/bootstrap2/admin/master.html", line 1, in <module>
    {% extends admin_base_template %}
  File "/usr/local/lib/python3.8/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 30, in <module>
    {% block page_body %}
  File "/usr/local/lib/python3.8/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 52, in <module>
    {% block messages %}
  File "/usr/local/lib/python3.8/site-packages/flask_admin/templates/bootstrap2/admin/base.html", line 53, in <module>
    {{ layout.messages() }}
  File "/usr/local/lib/python3.8/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.8/site-packages/flask_admin/templates/bootstrap2/admin/layout.html", line 70, in <module>
    {% macro messages() %}
jinja2.exceptions.UndefinedError: 'get_flashed_messages' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 65, in sentry_patched_wsgi_app
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 89, in __call__
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 52, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/wsgi.py", line 87, in __call__
    rv = self.app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 65, in <lambda>
    return SentryWsgiMiddleware(lambda *a, **kw: old_app(self, *a, **kw))(
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2334, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2320, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1766, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1744, in handle_user_exception
    return handler(e)
  File "/app/nook/utils/logging.py", line 161, in ___
    raise InternalServerError(ex)  # type: ignore
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: 'get_flashed_messages' is undefined
```

The error appears to be thrown in the template `flask_admin/templates/bootstrap2/admin/layout.html`, I also saw this error in `flask_admin/templates/bootstrap3/admin/layout.html"` when changing my template mode

**Comment by TitaniumHocker** [comment]
Can't reproduce this error, can you provide simple GIST to reproduce?

**Comment by bhaskart488** [comment]
+1

**Comment by ElLorans** [comment]
Superseded since bootstrap2 and 3 are not supported anymore.
