### ISSUE TITLE
Exclude field of type json from sorting in model by default

### ISSUE THREAD

**Issue by MerinRose** [pallets-eco/flask-admin#2009]
When the column_sortable_list is not given explicitly then if the model has a json field and when the sort is performed for that json field server error occurs.
My model is
class TestModel(db.Model):

    id = db.Column(primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    extra_properties = db.Column(JSON(), nullable=True)

Can that json field sort option be excluded from the admin page by default?

**Comment by TitaniumHocker** [comment]
Can't reproduce your example, I used `db.JSON` for column and this worked well.
Can you provide simple GIST to reproduce this error?

**Comment by MerinRose** [comment]
The trace is

Traceback (most recent call last):
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: could not identify an ordering operator for type json
LINE 2: FROM flask_user ORDER BY flask_user....
                                             ^
HINT:  Use an explicit ordering operator or modify the query.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask_restplus/api.py", line 584, in error_router
    return original_handler(e)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask_restplus/api.py", line 584, in error_router
    return original_handler(e)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask_admin/model/base.py", line 1970, in index_view
    view_args.search, view_args.filters, page_size=page_size)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/flask_admin/contrib/sqla/view.py", line 1079, in get_list
    query = query.all()
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/virtualenvs/flask_venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) could not identify an ordering operator for type json
LINE 2: FROM flask_user ORDER BY flask_user....
                                             ^
HINT:  Use an explicit ordering operator or modify the query.

[SQL: SELECT flask_user.id AS flask_user_id, flask_user.extra_properties AS flask_user_extra_properties, flask_user.created_at AS flask_user_created_at, flask_user.updated_at AS flask_user_updated_at, flask_user.username AS flask_user_username, flask_user.password_hash AS flask_user_password_hash 
FROM flask_user ORDER BY flask_user.extra_properties 
 LIMIT %(param_1)s]

**Comment by TitaniumHocker** [comment]
Seems like this error represents only on psycopg2 driver, sort works fine with SQLite3.

**Comment by MerinRose** [comment]
Well I made json fields non sort able by default by overriding scaffold_sortable_columns() function. That solved the server error. I know it is not the correct solution but that solved my issue temporarily. Any way thanks for your help.
