### ISSUE TITLE
Intial Server run is throwing TypeError: cannot unpack non-iterable EnumChoices object

### ISSUE THREAD

**Issue by tnniras** [pallets-eco/flask-admin#2113]
1. Just pulled a repo & installed requirements.txt in virtualenv
2. gettting below error when I'm starting the app

**### The Error:**

`Traceback (most recent call last):
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/examples/sqla/run_server.py", line 1, in <module>
    from admin import app
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/examples/sqla/admin/__init__.py", line 24, in <module>
    import admin.main
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/examples/sqla/admin/main.py", line 248, in <module>
    admin.add_view(UserAdmin(User, db.session))
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py", line 327, in __init__
    super(ModelView, self).__init__(model, name, category, endpoint, url, static_folder,
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/model/base.py", line 818, in __init__
    self._refresh_cache()
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/model/base.py", line 910, in _refresh_cache
    self._refresh_forms_cache()
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/model/base.py", line 835, in _refresh_forms_cache
    self._create_form_class = self.get_create_form()
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/model/base.py", line 1291, in get_create_form
    return self.get_form()
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/model/base.py", line 1248, in get_form
    return self.scaffold_form()
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py", line 745, in scaffold_form
    form_class = form.get_form(self.model, converter,
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/form.py", line 552, in get_form
    field = converter.convert(model, mapper, name, prop, field_args.get(name), hidden_pk)
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/form.py", line 263, in convert
    return converter(model=model, mapper=mapper, prop=prop,
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/form.py", line 307, in convert_choice_type
    accepted_values = [key for key, val in available_choices]
  File "/Users/tusharniras/Desktop/sanbox/flask-admin/venv/lib/python3.9/site-packages/flask_admin/contrib/sqla/form.py", line 307, in <listcomp>
    accepted_values = [key for key, val in available_choices]
TypeError: cannot unpack non-iterable EnumChoices object`

**Comment by bhargav-m01** [comment]
Facing the same issue. Can this be rectified.

**Comment by mihemihe** [comment]
Same error here after tried two times from scratch. To reproduce the issue:

virtualenv env -p python3
source env/bin/activate
pip install -r examples/sqla/requirements.txt
python3 examples/sqla/run_server.py




Traceback (most recent call last):
  File "/home/mihe/fa/flask-admin/examples/sqla/run_server.py", line 1, in <module>
    from admin import app
  File "/home/mihe/fa/flask-admin/examples/sqla/admin/__init__.py", line 24, in <module>
    import admin.main
  File "/home/mihe/fa/flask-admin/examples/sqla/admin/main.py", line 248, in <module>
    admin.add_view(UserAdmin(User, db.session))
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py", line 327, in __init__
    super(ModelView, self).__init__(model, name, category, endpoint, url, static_folder,
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/model/base.py", line 818, in __init__
    self._refresh_cache()
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/model/base.py", line 910, in _refresh_cache
    self._refresh_forms_cache()
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/model/base.py", line 835, in _refresh_forms_cache
    self._create_form_class = self.get_create_form()
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/model/base.py", line 1291, in get_create_form
    return self.get_form()
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/model/base.py", line 1248, in get_form
    return self.scaffold_form()
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/contrib/sqla/view.py", line 745, in scaffold_form
    form_class = form.get_form(self.model, converter,
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/contrib/sqla/form.py", line 552, in get_form
    field = converter.convert(model, mapper, name, prop, field_args.get(name), hidden_pk)
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/contrib/sqla/form.py", line 263, in convert
    return converter(model=model, mapper=mapper, prop=prop,
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/contrib/sqla/form.py", line 307, in convert_choice_type
    accepted_values = [key for key, val in available_choices]
  File "/home/mihe/fa/flask-admin/env/lib/python3.9/site-packages/flask_admin/contrib/sqla/form.py", line 307, in <listcomp>
    accepted_values = [key for key, val in available_choices]
TypeError: cannot unpack non-iterable EnumChoices object

**Comment by tnniras** [comment]
Is anyone working this issue? I was thinking about contributing for  this. Can I proceed?

**Comment by hkalex** [comment]
The temp solution I am using is changing the `form.py` line 307 from
```
accepted_values = [key for key, val in available_choices]
```

to
```
accepted_values = [key for key in available_choices]
```


I didn't test it completely. I just want to start the server and see the sample app.

**Comment by JanoschDeurer** [comment]
So there currently is no way to start the example application without modifying the packet?

**Comment by Am3ra** [comment]
Does it have anything to do with python version? I'm running with 3.9

Also, modifying the packet worked

**Comment by Ma27** [comment]
It seems as the issue gets fixed by downgrading [`SQLAlchemy-Utils`](https://pypi.org/project/SQLAlchemy-Utils/) to `0.36`.

**Comment by Aqueuse** [comment]
> It seems as the issue gets fixed by downgrading [`SQLAlchemy-Utils`](https://pypi.org/project/SQLAlchemy-Utils/) to `0.36`.

for me, now it trigger a new issue :

```
Traceback (most recent call last):
  File "examples/sqla/run_server.py", line 1, in <module>
    from admin import app
  File "/srv/flask-admin/examples/sqla/admin/__init__.py", line 24, in <module>
    import admin.main
  File "/srv/flask-admin/examples/sqla/admin/main.py", line 2, in <module>
    from admin.models import AVAILABLE_USER_TYPES, User, Post, Tag, Tree
  File "/srv/flask-admin/examples/sqla/admin/models.py", line 6, in <module>
    from sqlalchemy_utils import ChoiceType, EmailType, UUIDType, URLType, CurrencyType
  File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 14, in <module>
    from .orm import quote
  File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy/orm/query.py)
```

**Comment by qianshuyuank** [comment]
> > It seems as the issue gets fixed by downgrading [`SQLAlchemy-Utils`](https://pypi.org/project/SQLAlchemy-Utils/) to `0.36`.
> 
> for me, now it triggers a new issue :
> 
> ```
> Traceback (most recent call last):
>   File "examples/sqla/run_server.py", line 1, in <module>
>     from admin import app
>   File "/srv/flask-admin/examples/sqla/admin/__init__.py", line 24, in <module>
>     import admin.main
>   File "/srv/flask-admin/examples/sqla/admin/main.py", line 2, in <module>
>     from admin.models import AVAILABLE_USER_TYPES, User, Post, Tag, Tree
>   File "/srv/flask-admin/examples/sqla/admin/models.py", line 6, in <module>
>     from sqlalchemy_utils import ChoiceType, EmailType, UUIDType, URLType, CurrencyType
>   File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
>     from .aggregates import aggregated  # noqa
>   File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
>     from .functions.orm import get_column_key
>   File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
>     from .database import (  # noqa
>   File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 14, in <module>
>     from .orm import quote
>   File "/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
>     from sqlalchemy.orm.query import _ColumnEntity
> ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/srv/flask-admin/env/lib/python3.8/site-packages/sqlalchemy/orm/query.py)
> ```

You have installed SQLAlchemy 1.4.0. SQLAlchemy-utils is currently not compatible with SQLAlchemy > 1.4.0. The solution is to downgrade SQLAlchemy to 1.3.23
My pip list，work well：

Package            Version
------------------ --------
arrow              1.1.1
Babel              2.9.1
click              8.0.1
colorama           0.4.4
colour             0.1.5
dataclasses        0.8
dnspython          2.1.0
email-validator    1.1.3
Flask              2.0.1
Flask-Admin        1.5.8
Flask-BabelEx      0.9.4
Flask-SQLAlchemy   2.5.1
greenlet           1.1.1
idna               3.2
importlib-metadata 4.6.3
itsdangerous       2.0.1
Jinja2             3.0.1
MarkupSafe         2.0.1
pip                21.1.3
python-dateutil    2.8.2
pytz               2021.1
setuptools         57.1.0
six                1.16.0
speaklater         1.3
SQLAlchemy         1.3.23
SQLAlchemy-Utils   0.36.8
tablib             3.0.0
typing-extensions  3.10.0.0
Werkzeug           2.0.1
wheel              0.36.2
WTForms            2.3.3
zipp               3.5.0

**Comment by CarlyCarlyleAdams** [comment]
Just an update this is still not working SQLAlchemy-Utils==0.37.9 needed to drop back to SQLAlchemy-Utils==0.37.2

**Comment by ElLorans** [comment]
Fixed with [SqlAlchemy-Utils >= 0.38](https://github.com/pallets-eco/flask-admin/commit/18c3b28a8e25c1a58998bc18ddaf24f924eed53a) and [wtforms >= 2.3](https://github.com/pallets-eco/flask-admin/commit/a5c3baaa2b59d9face72ebd033f7562aebc7033c)
