### ISSUE TITLE
Flask Admin Incompatible With Modern Flask ( >=2.3)

### ISSUE THREAD

**Issue by mwheeler1982** [pallets-eco/flask-admin#2400]
I get the following error message when trying to start flask-admin . Based on my research, it looks like this has been broken since Flask 2.3. It looks like warnings were introduced in 2.2.0 that it was deprecated, then officially removed in 2.3.0 .

See here: https://flask.palletsprojects.com/en/3.0.x/changes/#version-2-3-0 and here: https://github.com/pallets/flask/pull/4692 . 

Traceback (most recent call last):
  File "/Users/user/venv/flask-admin-test/test.py", line 4, in <module>
    app = AdminApp()
  File "/Users/user/venv/flask-admin-test/lib/python3.9/site-packages/flask-admin-test/app.py", line 129, in __init__
    self.init_flask_app()
  File "/Users/user/venv/flask-admin-test/lib/python3.9/site-packages/flask-admin-test/app.py", line 300, in init_flask_app
    from flask.json import JSONEncoder
ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/Users/user/venv/flask-admin-test/lib/python3.9/site-packages/flask/json/__init__.py)

**Comment by maxnoe** [comment]
@mwheeler1982 The error is in your app code, not in flask-admin
