### ISSUE TITLE
Investigate Flask 3.1.0 compatibility

### ISSUE THREAD

**Issue by samuelhwilliams** [pallets-eco/flask-admin#2576]
@pamelafox and I have both seen some issues with latest (main branch) Flask-Admin with Python 3.12 (at least):

* Doing `pip install -e .[all] -r requirements/dev.txt` fails with this error:

```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/Users/sam/work/personal/flask-admin/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/sam/work/personal/flask-admin/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sam/work/personal/flask-admin/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/Users/sam/work/personal/flask-admin/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/private/var/folders/pl/sbgtddg1761g88rd26r4yspr0000gn/T/pip-build-env-fhjsnuiv/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/private/var/folders/pl/sbgtddg1761g88rd26r4yspr0000gn/T/pip-build-env-fhjsnuiv/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/private/var/folders/pl/sbgtddg1761g88rd26r4yspr0000gn/T/pip-build-env-fhjsnuiv/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

* And then once getting past that (by instead installing `requirements/tests.txt`, we're seeing issues around [Flask 3.1.0's support for partitioned cookies](https://github.com/pallets/flask/pull/5499):

```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------- Captured log call ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
ERROR    flask_admin.tests.conftest:app.py:875 Exception on /admin/secure/new/ [GET]
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 941, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 1322, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/sessions.py", line 387, in save_session
    response.set_cookie(
TypeError: Response.set_cookie() got an unexpected keyword argument 'partitioned'
ERROR    flask_admin.tests.conftest:app.py:948 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 941, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 1322, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/sessions.py", line 387, in save_session
    response.set_cookie(
TypeError: Response.set_cookie() got an unexpected keyword argument 'partitioned'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 941, in finalize_request
    response = self.process_response(response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/app.py", line 1322, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/vscode/.local/lib/python3.12/site-packages/flask/sessions.py", line 387, in save_session
    response.set_cookie(
TypeError: Response.set_cookie() got an unexpected keyword argument 'partitioned'
_______________________________________________________________________________________________________________________________________________________________________ test_export_csv _______________________________________________________________________________________________________________________________________________________________________

app = <Flask 'flask_admin.tests.conftest'>, admin = <flask_admin.base.Admin object at 0xffff71e1cfb0>

>   ???
E   assert 500 == 302
E    +  where 500 = <WrapperTestResponse streamed [500 INTERNAL SERVER ERROR]>.status_code

/Users/sam/work/personal/flask-admin/flask_admin/tests/test_model.py:658: AssertionError
```

**Comment by ElLorans** [comment]
The tests run fine though.
This is py3.12 env from a PR test suite.
Flask 3.1.1 is installed with wekzeug 3.1.3 and we get no errors, so I would imagine it's a flask-werkzeug compatibility issue.
I am closing this for now, but obviously feel free to reopen.

`py3.12: arrow==1.3.0,astroid==3.3.10,azure-core==1.34.0,azure-storage-blob==12.25.1,babel==2.17.0,beautifulsoup4==4.13.4,blinker==1.9.0,boto3==1.38.46,botocore==1.38.46,certifi==2025.6.15,cffi==1.17.1,charset-normalizer==3.4.2,click==8.2.1,colour==0.1.5,coverage==7.9.1,cryptography==45.0.4,dill==0.4.0,dnspython==2.7.0,email-validator==2.2.0,flake8==7.3.0,flask==3.1.1,flask-admin @ file:///home/runner/work/flask-admin/flask-admin,flask-babel==4.0.0,flask-sqlalchemy==3.1.1,geoalchemy2==0.17.1,greenlet==3.2.3,idna==3.10,iniconfig==2.1.0,isodate==0.7.2,isort==6.0.1,itsdangerous==2.2.0,jinja2==3.1.6,jmespath==1.0.1,markupsafe==3.0.2,mccabe==0.7.0,moto==5.1.6,numpy==2.3.1,packaging==25.0,peewee==3.18.1,pillow==11.2.1,platformdirs==4.3.8,pluggy==1.6.0,psycopg2-binary==2.9.10,pycodestyle==2.14.0,pycparser==2.22,pyflakes==3.4.0,pygments==2.19.2,pylint==3.3.7,pymongo==4.13.2,pytest==8.4.1,pytest-cov==6.2.1,python-dateutil==2.9.0.post0,pytz==2025.2,pyyaml==6.0.2,redis==6.2.0,requests==2.32.4,responses==0.25.7,s3transfer==0.13.0,shapely==2.1.1,six==1.17.0,soupsieve==2.7,sqlalchemy==2.0.41,sqlalchemy-citext==1.8.0,sqlalchemy-utils==0.41.2,tablib==3.8.0,tomlkit==0.13.3,types-python-dateutil==2.9.0.20250516,typing-extensions==4.14.0,urllib3==2.5.0,werkzeug==3.1.3,wtf-peewee==3.0.6,wtforms==3.2.1,xmltodict==0.14.2`
